services:
  traefik:
    image: traefik:v3.6.15
    restart: always
    init: true
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=backend
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
      - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /etc/traefik/dynamic:/etc/traefik/dynamic
    ports:
      - target: 80
        published: ${TRAEFIK_PORT:-80}
        protocol: tcp
      - target: 443
        published: ${TRAEFIK_SSL_PORT:-443}
        protocol: tcp
      - target: 443
        published: ${TRAEFIK_SSL_PORT:-443}
        protocol: udp
    networks:
      - backend
