services:
  traefik:
    container_name: traefik
    image: traefik:v3.3
    restart: unless-stopped
    init: true
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - TZ=${TIMEZONE:-Asia/Shanghai}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_PATH}gateways/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${CONFIG_PATH}gateways/traefik/dynamic:/etc/traefik/dynamic:ro
      - ${CONFIG_PATH}gateways/certbot/conf:/etc/traefik/certs:ro
      - ${DATA_PATH}traefik/acme:/etc/traefik/acme
      - ${LOG_PATH}traefik:/var/log/traefik
    ports:
      - "${TRAEFIK_PORT:-80}:80"
      - "${TRAEFIK_SSL_PORT:-443}:443"
      - "${TRAEFIK_SSL_PORT:-443}:443/udp"
    networks:
      - frontend
      - backend
