oss.{$SITE_ADDRESS} {
	header {
		Access-Control-Allow-Origin *
		Access-Control-Allow-Methods GET, HEAD, OPTIONS
		Access-Control-Allow-Headers Content-Type
	}
	encode zstd gzip

	@options method OPTIONS
	handle @options {
		respond "" 204
	}

	handle {
		file_server {
			fs oss-prd
		}
	}
}

oss-dev.{$SITE_ADDRESS} {
	header {
		Access-Control-Allow-Origin *
		Access-Control-Allow-Methods GET, HEAD, OPTIONS
		Access-Control-Allow-Headers Content-Type
	}
	encode zstd gzip

	@options method OPTIONS
	handle @options {
		respond "" 204
	}

	handle {
		file_server {
			fs oss-dev
		}
	}
}
