services:
  bytebase:
    image: bytebase/bytebase:3.15.1
    container_name: bytebase
    init: true
    ports:
      - "8380:8080"
    volumes:
      - ${DATA_PATH}bytebase/data:/var/opt/bytebase
    networks:
      - backend

