services:
  caddy:
    build:
      context: .
    container_name: caddy
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - CF_API_TOKEN=${CF_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${APP_CODE_PATH}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${CONFIG_PATH}caddy:/etc/caddy
      - ${DATA_PATH}caddy:/data/caddy
      - ${LOG_PATH}caddy:/srv/logs
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "diun.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - dozzle
      - authelia
      - php-roadrunner
      - php-fpm
    networks:
      - frontend
      - backend
