apiVersion: 1

datasources:
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    uid: victorialogs
    access: proxy
    url: http://victoria-logs:9428
    isDefault: false
    jsonData:
      maxLines: 1000
    editable: true
