apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: true
