# ==============================================================================
# S3 虚拟文件系统驱动配置 (sagikazarmark/caddy-fs-s3)
# 用于全局块 (Global Options) 中挂载外部 S3 存储桶为 Caddy 虚拟文件系统
# ==============================================================================

filesystem oss-prd s3 {
	bucket lunchbox-prd
	region cn-heyuan
	endpoint https://oss-cn-heyuan.aliyuncs.com
}

filesystem oss-dev s3 {
	bucket lunchbox-dev
	region cn-heyuan
	endpoint https://oss-cn-heyuan.aliyuncs.com
}
