services:
  pocketbase:
    build: .
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ${DATA_PATH}pocketbase/pb_data:/pb/pb_data
      - ${CONFIG_PATH}pocketbase/pb_public:/pb/pb_public
      - ${CONFIG_PATH}pocketbase/pb_hooks:/pb/pb_hooks
      - ${CONFIG_PATH}pocketbase/pb_migrations:/pb/pb_migrations
    networks:
      - backend
