services:
  open-bao:
    build:
      context: .
    container_name: open-bao
    restart: unless-stopped
    command:
      - server
    environment:
      - BAO_ADDR=http://127.0.0.1:8200
      - TZ=${TIMEZONE:-Asia/Shanghai}
    volumes:
      - ${DATA_PATH:-./data/}open-bao/data:/openbao/file
      - ${LOG_PATH:-./logs/}open-bao:/openbao/logs
    ports:
      - "${OPENBAO_PORT:-8200}:8200"
    networks:
      - backend
      - frontend
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1024M
