services:
  acme:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acme
    environment:
      - TZ=Asia/Shanghai
      - DOMAIN=${DOMAIN:-gaara.lol}
      - DNS_PROVIDER=${DNS_PROVIDER:-cloudflare}
      # Cloudflare
      - CLOUDFLARE_API_TOKEN=${DNS_CLOUDFLARE_API_TOKEN:-}
      # Aliyun
      - ALIYUN_ACCESS_KEY_ID=${ALIYUN_ACCESS_KEY_ID:-}
      - ALIYUN_ACCESS_KEY_SECRET=${ALIYUN_ACCESS_KEY_SECRET:-}
      - ACME_DEBUG=${ACME_DEBUG:-0}
    volumes:
      - ${DATA_PATH}acme:/acme.sh
      - ${DATA_PATH}ssl:/ssl
    restart: always
    networks:
      - backend

