services:
  jaeger-query:
    image: jaegertracing/jaeger-query:1.76
    container_name: jaeger-query
    restart: unless-stopped
    environment:
      SPAN_STORAGE_TYPE: grpc-plugin
      REMOTE_STORAGE_GRPC_HOST_PORT: victoria-traces:17271
    ports:
      - "16686:16686"
