services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.2.0
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ${DATA_PATH}uptime-kuma:/app/data
    networks:
      - backend