services:
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.20.1
    container_name: postgres-exporter
    restart: always
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?sslmode=disable
    networks:
      - backend
    expose:
      - 9187
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
