# =========================================================
# 日志配置 (Logging)
# =========================================================
map $time_iso8601 $custom_time {
    default "${time_iso8601}";
    ~^([^T]+)T([^+-]+)(.*)$ "$1 $2$3";
}

log_format main '$remote_addr - $remote_user [$custom_time] "$status | ${request_time}s | $request" '
                '${body_bytes_sent}B "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';

log_format json escape=json '{'
    '"time_local":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"request":"$request",'
    '"status":$status,'
    '"body_bytes_sent":$body_bytes_sent,'
    '"request_time":$request_time,'
    '"upstream_response_time":"$upstream_response_time",'
    '"http_referer":"$http_referer",'
    '"http_user_agent":"$http_user_agent"'
'}';

# 高并发下使用缓冲区异步写入
access_log /dev/stdout main buffer=32k flush=1s;
error_log  /dev/stderr warn;
