services:
  fluent-bit:
    image: fluent/fluent-bit:5.1
    container_name: fluent-bit
    restart: always
    ports:
      - "${FLUENT_BIT_FORWARD_PORT:-24224}:24224"
      - "${FLUENT_BIT_FORWARD_PORT:-24224}:24224/udp"
      - "${FLUENT_BIT_INGEST_PORT:-9880}:9880"
      - "${FLUENT_BIT_HTTP_PORT:-2020}:2020"
    volumes:
      - ${CONFIG_PATH}fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ${CONFIG_PATH}fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - ${LOG_PATH}:/var/log/apps:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - loki
    networks:
      - backend
      - frontend
