services:
  pgdog:
    image: ghcr.io/pgdogdev/pgdog:main
    container_name: pgdog
    ports:
      - "6432:6432"
    volumes:
      - ./pgdog.toml:/pgdog/pgdog.toml:ro
      - ./users.toml:/pgdog/users.toml:ro
    depends_on:
      - postgres
    restart: always
    networks:
      - backend
