services:
  wud:
    image: getwud/wud:9.1
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3200:3000"
    environment:
      - WUD_AUTH_ADMIN_USER=admin
      - WUD_AUTH_ADMIN_PASSWORD=admin_secret
    restart: always
    networks:
      - backend
      - frontend
