name: Build Redis Multi-arch Images

on:
  workflow_dispatch:
    inputs:
      redis_version:
        description: "Redis Base Version (e.g., 8.4-alpine)"
        required: true
        default: "8.4-alpine"
      tag:
        description: "Image Tag (e.g., latest)"
        required: true
        default: "latest"

jobs:
  build-redis-multiarch:
    runs-on: ubuntu-latest
    env:
      REDIS_VERSION: ${{ github.event.inputs.redis_version }}
      TAG: ${{ github.event.inputs.tag }}
      REGISTRY_DOCKERHUB: docker.io/jiaoio
      REGISTRY_REDHAT: quay.io/jiaoio
      REGISTRY_TENCENT: ccr.ccs.tencentyun.com/jiaoio

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to RedHat Registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REDHAT_REGISTRY_USERNAME }}
          password: ${{ secrets.REDHAT_REGISTRY_TOKEN }}

      - name: Login to Tencent Cloud Registry
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_REGISTRY_USERNAME }}
          password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}

      - name: Build and push Redis
        uses: docker/build-push-action@v6
        with:
          context: ./redis
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            CHANGE_SOURCE=false
            REDIS_VERSION=${{ env.REDIS_VERSION }}
          tags: |
            ${{ env.REGISTRY_DOCKERHUB }}/redis:${{ env.TAG }}
            ${{ env.REGISTRY_REDHAT }}/redis:${{ env.TAG }}
            ${{ env.REGISTRY_TENCENT }}/redis:${{ env.TAG }}
