services:
  rclone:
    image: rclone/rclone:1.74
    container_name: rclone
    restart: "no"
    entrypoint: ["rclone"]
    command: ["version"]
    volumes:
      - ./rclone.conf:/config/rclone.conf:ro
    networks:
      - backend

networks:
  backend:
    external: true
