services:
  valkey:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valkey_server
    restart: always
    environment:
      - VALKEY_PASSWORD=${REDIS_PASSWORD}
    sysctls:
      - net.core.somaxconn=4096
    ports:
      - "6379:6379"
    volumes:
      - ${DATA_PATH}valkey:/data
    networks:
      - backend

