services:
  casdoor:
    image: casbin/casdoor:latest
    container_name: casdoor
    restart: always
    ports:
      - "8300:8000"
    environment:
      - GIN_MODE=release
    volumes:
      - ${CONF_PATH}/conf:/conf
      - ${DATA_PATH}casdoor/logs:/logs
