[garage]
type = s3
provider = Other
env_auth = false
access_key_id = GKfd16f76e81fb861a868a01b9b19452ad
secret_access_key = 18d5eda476ff7fb88f0bec38eae3a5e468020ae6dfc610defe2f3f72a65c4339
region = garage
endpoint = http://127.0.0.1:3900
force_path_style = true
acl = private
bucket_acl = private

[ali-oss]
type = s3
provider = Alibaba
env_auth = false
access_key_id = YOUR_ALIYUN_ACCESS_KEY_ID
secret_access_key = YOUR_ALIYUN_SECRET_ACCESS_KEY
endpoint = oss-cn-hangzhou.aliyuncs.com
acl = private
storage_class = Standard

[cloudflare-r2]
type = s3
provider = Cloudflare
env_auth = false
access_key_id = YOUR_CLOUDFLARE_R2_ACCESS_KEY_ID
secret_access_key = YOUR_CLOUDFLARE_R2_SECRET_ACCESS_KEY
region = auto
endpoint = https://YOUR_ACCOUNT_ID.r2.cloudflarestorage.com
acl = private
no_check_bucket = true
