(fpm-app) {
	{args[0]} {
		import ../snippets/request-log.conf
		import ../snippets/security.conf
		import ../snippets/waf.conf
		encode zstd gzip

		root * {args[1]}

		# 1. 公共存储目录直接响应
		handle /storage/* {
			root * {args[1]}
			file_server
			header Cache-Control "public, max-age=604800" # 7天
		}

		# 2. 公共静态资源直接响应
		@static {
			path_regexp \.(js|css|png|jpg|jpeg|ico|woff2|woff|ttf|svg|webp|gif|map)$
		}
		handle @static {
			root * {args[1]}
			file_server {
				precompressed gzip br # 自动查找 .gz / .br 预压缩文件
			}
			header Cache-Control "public, max-age=31536000, immutable"
		}

		# 3. 默认兜底处理 (转发至 PHP-FPM)
		php_fastcgi {args[2]}
		file_server
	}
}
