x-chatwoot-base: &chatwoot-base
  image: chatwoot/chatwoot:${CHATWOOT_VERSION:-v4.17.1}
  restart: always
  environment:
    - NODE_ENV=production
    - RAILS_ENV=production
    - INSTALLATION_ENV=docker
    - RAILS_LOG_TO_STDOUT=true
    - ACTIVE_STORAGE_SERVICE=local
    - SECRET_KEY_BASE=${CHATWOOT_SECRET_KEY_BASE:-2f88195a623091722883ef4b1ef40409a6915b22b7a97ebfbcfda3b3bc229983a0429a39908cf818c3efb3fbfa4b6bc8a9b2075775f0a0d9bcfcb0677aa477db}
    - FRONTEND_URL=${CHATWOOT_FRONTEND_URL:-http://chat.${SITE_ADDRESS}}
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_USERNAME=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DATABASE=${CHATWOOT_DB_NAME:-chatwoot}
    - REDIS_URL=redis://:${REDIS_PASSWORD}@valkey:6379
    - REDIS_PASSWORD=${REDIS_PASSWORD}
  volumes:
    - ${DATA_PATH}chatwoot/storage:/app/storage
  depends_on:
    postgres:
      condition: service_started
    valkey:
      condition: service_started

services:
  chatwoot:
    <<: *chatwoot-base
    container_name: chatwoot
    ports:
      - "${CHATWOOT_PORT:-3000}:3000"
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    networks:
      - backend
      - frontend

  chatwoot-sidekiq:
    <<: *chatwoot-base
    container_name: chatwoot-sidekiq
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    networks:
      - backend
